### PR TITLE
Extra master

### PR DESCRIPTION
**Pull request by itsalinazarpour**
I think it's better to delete the favicon!!!
@Yasaman-Ghobadi what do you think about it?
If it's appropriate, please merge it in.

### CODE REVIEW

**Comment by itsalinazarpour** [comment]
helloooo @Yasaman-Ghobadi

**Comment by Yasaman-Ghobadi** [comment]
I will check it now

**Comment by Yasaman-Ghobadi** [comment]
I can't find your pull request
Please send the exact link in here
Thanks.

**Comment by itsalinazarpour** [comment]
Hi. I realized that you didn't merge this pull yet. It's a great honor if you do it for me. BDW it's a tiny change in one of my projects that you were invited to it. I mean this is a fake pull request, not a real one.

**Pull request merged**
